### DISCUSSION TITLE
Run TD3 in Isaac Lab

### DISCUSSION THREAD

**Discussion by shaoxiang** [Toni-SM/skrl#261] [Q&A] [answered]
I want to run the TD3 algorithm in Isaac Lab, so I tried upgrading skrl to version 1.4.0 using the following command:
`./isaaclab.sh -p -m pip install git+https://github.com/Toni-SM/skrl.git@develop`
PPO can run successfully for the task, but TD3 may encounter exceptions:

> [skrl:WARNING] agents:TD3: No smooth regularization noise specified to reduce variance during training                                                                                                                            | 80/4800 [01:30<1:29:16,  1.13s/it]
> Error executing job with overrides: []
> Traceback (most recent call last):
>   File "D:\omniverse\pkg\isaac-lab\mylab\IsaacLab\source\extensions\omni.isaac.lab_tasks\omni\isaac\lab_tasks\utils\hydra.py", line 99, in hydra_main
>     func(env_cfg, agent_cfg, *args, **kwargs)
>   File "D:\omniverse\pkg\isaac-lab\mylab\IsaacLab\source\standalone\workflows\skrl\train.py", line 179, in main
>     runner.run()
>   File "D:\anaconda3\envs\my_isaaclab\lib\site-packages\skrl\utils\runner\torch\runner.py", line 481, in run
>     self._trainer.train()
>   File "D:\anaconda3\envs\my_isaaclab\lib\site-packages\skrl\trainers\torch\sequential.py", line 86, in train
>     self.single_agent_train()
>   File "D:\anaconda3\envs\my_isaaclab\lib\site-packages\skrl\trainers\torch\base.py", line 193, in single_agent_train
>     actions = self.agents.act(states, timestep=timestep, timesteps=self.timesteps)[0]
>   File "D:\anaconda3\envs\my_isaaclab\lib\site-packages\skrl\agents\torch\td3\td3.py", line 262, in act
>     noises = self._exploration_noise.sample(actions.shape)
> AttributeError: 'float' object has no attribute 'sample'
> 

My space configuration is as follows:
```
action_space = 3
observation_space = 21
```

My **skrl_td3_cfg.yaml** configuration is as follows:
```
seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [512, 512]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 512]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: 15625  # automatically determined (same as agent:rollouts)

# configure and instantiate the agent (visit its documentation to see all the options)
# https://skrl.readthedocs.io/en/latest/api/agents/td3.html#configuration-and-hyperparameters
agent:
  class: TD3
  gradient_steps: 1
  batch_size: 4096
  discount_factor: 0.99
  polyak: 0.005
  rollouts: 15625
  actor_learning_rate: 5e-4    # actor learning rate
  critic_learning_rate: 5e-4   # critic learning rate
  learning_rate_scheduler": KLAdaptiveLR        # learning rate scheduler class (see torch.optim.lr_scheduler)
  learning_rate_scheduler_kwargs":              # learning rate scheduler's kwargs (e.g. {"step_size": 1e-3})
    step_size: 1e-3

  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 20
  learning_starts: 20
  grad_norm_clip: 0

  exploration:
    noise: 0.1              # exploration noise
    initial_scale: 1.0      # initial scale for the noise
    final_scale: 1e-3       # final scale for the noise
    timesteps: None         # timesteps for the noise decay

  policy_delay: 2                        # policy delay update with respect to critic update
  smooth_regularization_noise": None    # smooth noise for regularization
  smooth_regularization_clip": 0.5      # clip for smooth regularization
  rewards_shaper: None         # rewards shaping function: Callable(reward, timestep, timesteps) -> reward
  mixed_precision: False       # enable automatic mixed precision for higher performance

  # logging and checkpoint
  experiment:
    directory: "kaya_direct"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto
    store_separately: False          # whether to store checkpoints separately

# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 4800
  environment_info: log

```
Looking forward to receiving help, thank you very much.

**Comment by shaoxiang** [comment]
I tried running the examples in **examples/isaaclab** and found some strange running phenomena.
When running **torch_cartpole_ppo.py**, everything is normal, but when running **torch_ant_td3.py**, the robot disappears from the scene, and the same is true when running the **Isaac-Cartpole-v0** task. 
My Isaac Lab version is the latest, and Isaac Sim is 4.2.0.
This image shows the loss effect during training.
![image](https://github.com/user-attachments/assets/4d7f7440-60a5-49e2-85f6-976e320437ea)

**Comment by Toni-SM** [comment, marked as answer]
Hi @shaoxiang 

The next is an example of the TD3 agent config for the Isaac Lab `Isaac-Ant-Direct-v0` task.
Please, note how the models are defined (model keys use the same name as [TD3's model keys](https://skrl.readthedocs.io/en/latest/api/agents/td3.html#models)). Also, the noise, in `yaml` format is defined using two keys: `noise` (noise class) and `noise_kwargs` (class arguments), same for `smooth_regularization_noise` .

<br>

`skrl_td3_cfg.yaml` file:
```yaml
seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256]
        activations: relu
    output: tanh(ACTIONS)
  target_policy:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256]
        activations: relu
    output: tanh(ACTIONS)
  critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([STATES, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([STATES, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  target_critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([STATES, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE
  target_critic_2:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: concatenate([STATES, ACTIONS])
        layers: [512, 256]
        activations: relu
    output: ONE


# Rollout buffer
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: 15625


# TD3 agent configuration (field names are from TD3_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/td3.html
agent:
  class: TD3
  gradient_steps: 1
  batch_size: 4096
  discount_factor: 0.99
  polyak: 0.005
  actor_learning_rate: 5.0e-4
  critic_learning_rate: 5.0e-4
  learning_rate_scheduler: null
  learning_rate_scheduler_kwargs: null
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  random_timesteps: 80
  learning_starts: 80
  grad_norm_clip: 0
  exploration:
    noise: GaussianNoise
    noise_kwargs:
      mean: 0.0
      std: 0.1
    initial_scale: 1.0
    final_scale: 1.0e-3
    timesteps: null
  policy_delay: 2
  smooth_regularization_noise: GaussianNoise
  smooth_regularization_noise_kwargs:
    mean: 0.0
    std: 0.2
  smooth_regularization_clip: 0.5
  rewards_shaper: null
  mixed_precision: False
  # logging and checkpoint
  experiment:
    directory: "ant_direct"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 160000
  environment_info: log
```

Regarding the Isaac Lab code, the following modification is necessary to train with the skrl's TD3 agent.

1. Update skrl's train.py script to include the `"TD3"` agent: 
    
    https://github.com/isaac-sim/IsaacLab/blob/ea766783996d57e9f60b6c58c739c5fa4fbe79c5/source/standalone/workflows/skrl/train.py#L43 

2. Update `direct/ant` task to include the agent configuration for TD3:

    `"skrl_td3_cfg_entry_point": f"{agents.__name__}:skrl_td3_cfg.yaml",`

    https://github.com/isaac-sim/IsaacLab/blob/ea766783996d57e9f60b6c58c739c5fa4fbe79c5/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/direct/ant/__init__.py#L26

3. Update the `direct/ant` task to define limits for the `action_space` using Gymnasium.

    `action_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(8,))`

    https://github.com/isaac-sim/IsaacLab/blob/ea766783996d57e9f60b6c58c739c5fa4fbe79c5/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/direct/ant/ant_env.py#L27

    This point is very important!
    Since TD3 performs random exploration at the beginning (see TD3 `random_timesteps` config), if the space is not limited, the sampled random actions are not bounded ([with values close to Inf](https://gymnasium.farama.org/api/spaces/fundamental/#gymnasium.spaces.Box.sample)) and the robot will disappear from the scene (same problem when running the skrl's `torch_cartpole_ppo.py` standalone script) 

<hr>

I forgot, you can run then the training as follows (with 64 environments: see https://github.com/Toni-SM/skrl/discussions/83#discussioncomment-6273097 and this [reddit post](https://www.reddit.com/r/reinforcementlearning/comments/12h1faq/isaac_gym_with_offpolicy_algorithms/)):

```
./isaaclab.sh -p source/standalone/workflows/skrl/train.py --task Isaac-Ant-Direct-v0 --algorithm TD3 --num_env 64 --headless
```
