### DISCUSSION TITLE
IPPO configuration settings

### DISCUSSION THREAD

**Discussion by JulienHansen** [Toni-SM/skrl#270] [Q&A] [answered]
Hi @Toni-SM ,

I believe I don't fully understand the model instantiator. I used the following IPPO YAML file for my application, which involves two drones—one attacking and the other defending. What I can't comprehend is that when testing my environment and allowing the attacker to reach a desired position with the following reward function:

```py
    def _get_rewards(self) -> dict[str, torch.Tensor]:
        rewards = {}
        for agent in self.cfg.possible_agents:
            if agent == "drone_attack":
                lin_vel = torch.sum(torch.square(self._drone_attack.data.root_lin_vel_b), dim=1)
                ang_vel = torch.sum(torch.square(self._drone_attack.data.root_ang_vel_b), dim=1)
                distance_to_goal = torch.linalg.norm(self._desired_pos_w - self._drone_attack.data.root_pos_w, dim=1)
                distance_to_goal_mapped = 1 - torch.tanh(distance_to_goal / 0.8)
                reward = (
                    lin_vel * self.cfg.lin_vel_reward_scale +
                    ang_vel * self.cfg.ang_vel_reward_scale +
                    distance_to_goal_mapped * self.cfg.distance_to_goal_reward_scale
                ) * self.step_dt
            elif agent == "drone_defense":
                # Implement the defender's reward logic here
                pass
            else:
                raise ValueError(f"Unknown agent key: {agent}")
            
            rewards[agent] = reward
            # Logging
            #self._episode_sums[f"{agent}_reward"] += reward

        return rewards
```

the one defending learn to fly even though with IPPO i would have though it would only stay on the ground as it doesn't have any reward, here is my IPPO config, am i missing something ? 

```yaml 

seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# IPPO agent configuration (field names are from IPPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/multi_agents/ippo.html
agent:
  class: IPPO
  rollouts: 16
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 5.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.016
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.0
  value_loss_scale: 2.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "quadcopter_direct"
    experiment_name: "100k"
    write_interval: auto
    checkpoint_interval: auto
    wandb: True
    wandb_kwargs:



# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 36000
  environment_info: log

```

Thanks in advance
