### DISCUSSION TITLE
I get problems when trying to deploy a trained PPO Agent

### DISCUSSION THREAD

**Discussion by AndreaRossetto** [Toni-SM/skrl#327] [Q&A]
Hi,
I'm trying to load my PPO agent from the saved checkpoint and use the model on real world, I save the checkpoints with `store_separately: True` so I have these files:

```
best_optimizer.pt
best_policy.pt
best_value.pt
best_value_preprocessor.pt
```
I followed this [Discussion](https://github.com/Toni-SM/skrl/discussions/87) and I created the Policy class

the model in the YAML

```
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES["robot-state"]
        layers:
          - linear: [512]
          - linear: [256]
          - linear: [128]
        activations: ["elu", "elu", "elu"]
    output: ACTIONS
    output_scale : 2.0
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES["robot-state"]
        layers:
          - linear: [512]
          - linear: [256]
          - linear: [128]
        activations: ["elu", "elu", "elu"]
    output: ONE
```

```
# define only the policy
class Policy(GaussianMixin, Model):
    def __init__(self, observation_space, action_space, device, clip_actions=False,
                clip_log_std=True, min_log_std=-20, max_log_std=2, reduction="sum"):

        Model.__init__(self, observation_space, action_space, device)
        GaussianMixin.__init__(self, clip_actions, clip_log_std, min_log_std, max_log_std, reduction)

        print(self.num_observations)
        self.net = nn.Sequential(   nn.Linear(self.num_observations, 512),
                                    nn.LazyLinear(512),
                                    nn.ELU(),
                                    nn.LazyLinear(256),
                                    nn.ELU(),
                                    nn.LazyLinear(128),
                                    nn.ELU(),
                                )
        self.log_std_parameter = nn.Parameter(torch.zeros(self.num_actions))

    def compute(self, inputs, role):
        return self.net(inputs["states"]), self.log_std_parameter, {}
```
then 
```

lin_vel = [0,0,0]
ang_vel = [0,0,0]
euler_vel = [0,0,0]
 command_vel = [0,0,0,0,0,0,0]
pelvis_height = [0]
joint_pos = [0,0,0,0,0,0,0,0,0,0,0,0]
joint_vel = [0,0,0,0,0,0,0,0,0,0,0,0]
actions = [0,0,0,0,0,0,0,0,0,0,0,0]

self.observation_space = torch.tensor([lin_vel + ang_vel + euler_vel + command_vel + pelvis_height + joint_pos + joint_vel + actions], device=device)
 self.action_space = torch.zeros(1, 12, device=device)

# instantiate state-preprocessor and the policy
state_preprocessor = RunningStandardScaler(self.observation_space, device=device)
self.policy = Policy(self.observation_space, self.action_space, device=device).to(device)

 # load checkpoints
state_preprocessor.load_state_dict(torch.load(statePreprocessor, weights_only=True))
self.policy.load(DNNmodel)  # same as policy.load_state_dict(torch.load("policy_1600.pt"))
```
but on lines 
```
state_preprocessor = RunningStandardScaler(self.observation_space, device=device)
self.policy = Policy(self.observation_space, self.action_space, device=device).to(device)
```
 I get the error 

`AttributeError: 'Tensor' object has no attribute 'is_np_flattenable'`

What I'm doing wrong?
