### DISCUSSION TITLE
Relationship between the skrl models and Isaac Gym models

### DISCUSSION THREAD

**Discussion by famora2** [Toni-SM/skrl#45] [General]
Hello,

according to the documentation (https://skrl.readthedocs.io/en/latest/intro/getting_started.html#models), this library creates another model that functions as the agent's brain. How are these models connected to the model that is for example defined in the Isaac Gym settings (see below). As you can in the below example of Cartpole from Isaac Gym, it uses the `a2c_continuous` algorithm and utilizes a MLP with two layers as its brain, right?

```
params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [32, 32]
      activation: elu
      
      initializer:
        name: default
      regularizer:
        name: None
```
