### ISSUE TITLE
[Bug] 'self._clip_actions' automatically changes from True to False

### ISSUE THREAD

**Issue by KevinGeng3** [Toni-SM/skrl#249]
### Description

When I trained IPPO with Isaaclab, I found that 'self._clip_actions' would automatically change from True to False. 
Here is part of the cfg file:
```
# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [64, 64]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [64, 64]
        activations: elu
    output: ONE
```
As you can see, I set 'clip_actions' of policy network to be true.
And Here is the output of instantiating model:
```
class GaussianDeterministicModel(GaussianMixin, DeterministicMixin, Model):
    def __init__(self, observation_space, action_space, device):
        Model.__init__(self, observation_space, action_space, device)
        GaussianMixin.__init__(self,
                               clip_actions=True,
                               clip_log_std=True,
                               min_log_std=-20.0,
                               max_log_std=2.0,
                               role="policy")
        DeterministicMixin.__init__(self, clip_actions=False, role="value")

        self.net_container = nn.Sequential(
            nn.LazyLinear(out_features=64),
            nn.ELU(),
            nn.LazyLinear(out_features=64),
            nn.ELU(),
        )
        self.policy_layer = nn.LazyLinear(out_features=self.num_actions)
        self.value_layer = nn.LazyLinear(out_features=1)
        self.log_std_parameter = nn.Parameter(0.0 * torch.ones(self.num_actions))

    def act(self, inputs, role):
        if role == "policy":
            return GaussianMixin.act(self, inputs, role)
        elif role == "value":
            return DeterministicMixin.act(self, inputs, role)
    
    def compute(self, inputs, role=""):
        if role == "policy":
            net = self.net_container(inputs["states"])
            self._shared_output = net
            output = self.policy_layer(net)
            return output, self.log_std_parameter, {}
        elif role == "value":
            if self._shared_output is None:
                net = self.net_container(inputs["states"])
                shared_output = net
            else:
                shared_output = self._shared_output
            self._shared_output = None
            output = self.value_layer(shared_output)
            return output, {}
```
As you can see, 'clip_actions' of GaussianMixin model was set to be True.

And I print 'self._clip_actions' in \_\_init\_\_() of GaussianMixin, it was True. **However**, when I print "self._clip_actions" in act() of GaussianMixin, it was False! It means that 'self._clip_actions' was changed somewhere else and thus the actions was not clamped successfully, but sadly I could not find that place.

So does anyone know how to handle this problem? Thank you a lot!

### What skrl version are you using?
1.3.0
---

### What ML framework/library version are you using?
IsaacLab
