### ISSUE TITLE
Wandb early stopping for HP sweep do not work.

### ISSUE THREAD

**Issue by btabia** [Toni-SM/skrl#258]
### Description

Hello, 

When trying to run a sweep in order to search for Hyper parameter. I figured out that a sweep wand config that worked for SB3 did not work for skrl. For instance, failing runs won't be stopped by wandb when using skrl. Have you had the same issue?

Here the sweeping configuration and wandb configuration in skrl: 

```
  experiment: 
    directory: "./training_data/"
    experiment_name: ""
    write_interval: 512 # Not used, we use the rollout value instead
    checkpoint_interval: 1000
    store_separately: False
    wandb: True 
    wandb_kwargs: 
      project: project1
      mode: online
      monitor_gym: True
      sync_tensorboard: True
```

```
program: script/train.py
method: bayes
metric:
  name: Reward / Total reward (mean)
  goal: maximize
early_terminate: 
  type: hyperband
  #strict: True
  min_iter: 10
  eta: 3
parameters:
  train.RL.algo.rollouts:
    values: [512]
  train.RL.algo.learning_epochs:
    values: [10]
  train.RL.algo.mini_batch_size:
    values: [32,64,128]
  train.RL.algo.value_loss_scale:
    distribution: uniform
    min: 0.5
    max: 1
  train.RL.algo.kl_threshold:
    distribution: uniform
    min: 0.008
    max: 0.01
  train.RL.algo.grad_norm_clip:
    distribution: uniform
    min: 0.5
    max: 1
  train.RL.algo.learning_rate:
    distribution: uniform
    min: 1e-4
    max: 1e-3
command:
  - ${env}
  - ${CUDA_VISIBLE_DEVICES}
  - .local/share/ov/pkg/isaac-sim-4.2.0/python.sh
  - ${program}
  - ${args_no_hyphens}

```

### What skrl version are you using?

1.3.0

### What ML framework/library version are you using?

2.4.0+cu118

### Additional system information

Ubuntu 22.04
