### ISSUE TITLE
Clip action bug in SharedModel

### ISSUE THREAD

**Issue by ricard-inho** [Toni-SM/skrl#272]
### Description

When using the following configuration in IsaacLab for training PPO, the actions of the policy are not getting clip. I can see the flag passing on the initialization of the class and setting it to true but is not getting set because later on the act function is back to false. When I look at the actions inside the IsaacLab loop they are not clipped. Clip action works when `separate` is set to `True`.
```
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [32, 32]
        activations: elu
    output: tanh(ACTIONS)
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [32, 32]
        activations: elu
    output: ONE
```

### What skrl version are you using?

1.4.1

### What ML framework/library version are you using?

Isaaclab docker
